Include the YWGC service area
cherryontech/ywgc pull request #112
Opened 2023-07-05 16:51 UTC by NurkaAmre

## Context

[link to Jira card](https://ywgc.atlassian.net/jira/software/projects/YWGC/boards/1?selectedIssue=YWGC-27)

## Work done

- [ ] Include the YWGC service area

## Manual testing instructions

- [ ] Resize the screen to a smaller size to simulate a mobile device.
- [ ]  Check if the website is responsive and adjusts properly to the smaller screen size.

## Gotchas/What I learned

- [ ] Improve accessibility in the ServiceArea component and integrate Google Maps

2023-07-06 15:13 UTC, novellac commented on src/components/ServiceArea.jsx
> +        <p className='text-xl my-10 md:text-center'>We are proudly located in Detroit, Michigan. We service the <span className='font-bold'>Detroit, Highland Park, Hamtramck,</span> and <span classNa
question: Why are we using a `<br />` tag in here? On different screen sizes it inserts line breaks which look bad. Remember, we are not coding just for one screen size, but all screen sizes, so if you are unsure whether or not there must be a line break between some text, it is best to ask the designer how the design should look at different screen sizes.

2023-07-06 15:16 UTC, novellac requested changes
issue: When you create a PR, please give us more specific testing instructions. Although I can check if the website is responsive, I don't know what I'm looking for, so I need your guidance as the dev. What did you change? What should I expect to see now? If your PR involves anything that is specific to a screen reader, should I try it out on a screen reader too? etc.

2023-07-11 22:28 UTC, novellac approved these changes
Looks great, thanks!

2023-07-12 01:12 UTC, novellac requested changes
Issue: I just looked at the [Figma](https://www.figma.com/file/0jts9Si8UJTQGraMQcFRUL/YWGC?type=design&node-id=701-1472&mode=design&t=LfGiCR53GG4KoA5i-0) again and realised that the text is not centered, so please left-align it.

2023-07-12 01:20 UTC, alliequintano requested changes

2023-07-12 01:20 UTC, alliequintano commented on src/index.js
> -      </div>
Can you please leave the existing footer contents as is since it is out of scope to remove or change it in this story card?

2023-07-12 16:04 UTC, novellac requested changes
Almost there! Please address my comment about centered text, as well as Allie's comment about not deleting unrelated code.

2023-07-13 17:19 UTC, jaynaxissa reviewed
Just making sure we both have a consistent design. Let's communicate and ask each other more. Other than that I think the rest looks great! 😊

2023-07-20 10:38 UTC, jaynaxissa submitted a review, later dismissed

2023-07-20 10:38 UTC, jaynaxissa commented on src/index.js
Issue: There's an error from here that won't allow Netlifly to deploy. Can we double check? It looks like it has something to do with a JSX fragment.

2023-07-20 13:04 UTC, novellac commented on src/index.js
> +        <h1 className='text-center text-white'>
issue: We should only have one h1 per page, and I think since the `BrowserRouter` is on this file, we'll be getting our h1's from those pages.

2023-07-24 17:05 UTC, alliequintano requested changes

2023-07-24 17:05 UTC, alliequintano commented on src/index.js
> +    </div>
It looks like this is overwriting the footer from the main branch. The copyright changes have been merged into main so i think you should be able to merge main into your branch and not need to make any changes to this? i'm not completely sure what's going on but please view your local version and/or deploy preview and compare it to what's deployed live already at [yorkshirewo](https://yorkshirewoodsgroundcrew.com/) to make sure you're not introducing a regression into the site.

2023-07-25 08:49 UTC, jaynaxissa commented on src/components/ServiceArea.jsx
> +        <hr className='w-[180px] md:w-[720px] h-px mx-auto mt-2 mb-10 md:mb-2 bg-gray-500 border-0 rounded dark:bg-gray-700' />
Nitpicking (nb): Just got a comment from our mentor, we have to check with the designer about the underline hr tag, as the length is not using Tailwind prefixes.

2023-07-25 08:49 UTC, jaynaxissa commented on src/components/ServiceArea.jsx
> +        <h2 className='text-center mb-3 text-5xl md:text-6xl font-header'>Areas We Serve</h2>
Note (nb): I'm using text-4xl md:text-6xl at the moment. Not sure if we have to use the same size as it is a page title. Could we mention this to the designer?

2023-07-26 01:51 UTC, alliequintano approved these changes
Nice job!

2023-07-31 16:27 UTC, alliequintano approved these changes

2023-07-31 17:14 UTC, merged

2023-08-01 04:09 UTC, jaynaxissa commented
Looks great to me. I can see that it's already merged so good job!