Fix services
cherryontech/ywgc pull request #121
Opened 2023-07-13 14:38 UTC by jaynaxissa

## Refactoring the services component

https://ywgc.atlassian.net/browse/YWGC-38?atlOrigin=eyJpIjoiMGYwZGU3ZjRhOWFjNGY3NDk2ZmQzNDY2NzQ5ZGJjODAiLCJwIjoiaiJ9

## Work done
- Made all the changes based on the new design on figma (add horizontal line, make sure the font size are switching to the right font size when it comes to different screen size)

## Manual testing instructions
- Responsive
- Make sure the design is accessible range from wide screen to mobile screen size.
- Works locally

## Gotchas/What I learned

2023-07-13 14:52 UTC, novellac commented on src/pages/Home.jsx
> +    <div>
Question: Why did you add this extra `div`? It seems out of scope for the card.

2023-07-13 14:54 UTC, novellac commented on src/components/Services.jsx
> +      </li>
issue: This puts all the service items inside one `li`, when they should each have their own `li`. The impact of this is that screen readers and other assistive technology will assume this is a list with _one_ item, when it's really a list with more than one item.

2023-07-13 14:55 UTC, novellac requested changes
issue: The manual testing instructions aren't specific enough. Please let me know what I should be testing when I open the preview link. For example, should I be checking the way the section heading looks? Should I be checking the number of items? Should I be checking the placement of the icon? Etc.

2023-07-16 23:45 UTC, alliequintano approved these changes
Thanks for the more detailed testing instructions! Looks good to me. It might be worth getting an approval from @ajkarczewski before merging since a lot of the details for this PR have to do with the design.

2023-07-17 03:08 UTC, ajkarczewski approved these changes
Nice work! Looks good so far :)

2023-07-18 13:57 UTC, novellac approved these changes

2023-07-18 14:45 UTC, merged